# Write a Python program to find common values between two arrays and get unique values of an array(Use numpy)
import numpy as np

r = int(input("Enter the rows : "))
c = int(input("Enter the columns : "))
print("Matrix - 1")
print("Enter ", r * c, "elements seprated by space in a single line ")
a = list(map(int, input().split()))
ma = np.array(a).reshape(r, c)
print("Matrix - 2")
print("Enter ", r * c, "elements seprated by space in a single line")
b = list(map(int, input().split()))
mb = np.array(b).reshape(r, c)
print("\nMatrix - 1 Elements")
print(ma)
print("\nMatrix - 2 Elements")
print(mb)
common_values = np.intersect1d(ma, mb)
unique_elementsma = np.setdiff1d(ma, mb)
unique_elementsmb = np.setdiff1d(mb, ma)
print('\nCommon values in both matrices ')
print(common_values)
print('\nUnique values in both matrices ')
print(unique_elementsma, unique_elementsmb)
